// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMYK6EG_Gfyw591o8Db8Dn1ovGc18S6NI',
    appId: '1:544463953274:android:e27c263e541e6013628ac3',
    messagingSenderId: '544463953274',
    projectId: 'sparrow-37209',
    storageBucket: 'sparrow-37209.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIqwgVJeoZqbkwWc39UsYiFox9dvnfux8',
    appId: '1:544463953274:ios:ccebe3b673c75bc7628ac3',
    messagingSenderId: '544463953274',
    projectId: 'sparrow-37209',
    storageBucket: 'sparrow-37209.appspot.com',
    iosClientId: '544463953274-j1p7emlk3k4cvccvnnkasd566u787o3t.apps.googleusercontent.com',
    iosBundleId: 'com.sparrows.sparrow',
  );
}
